/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0c1326",
        "on-surface": "#dbe2fc",
        "surface-bright": "#32394d",
        "surface-variant": "#2d3449",
        "surface-dim": "#0c1326",
        "surface-container-lowest": "#060d20",
        "surface-container-low": "#141b2e",
        "surface-container": "#181f32",
        "surface-container-high": "#23293d",
        "surface-container-highest": "#2d3449",
        "on-surface-variant": "#c7c4d7",
        "outline": "#908fa0",
        "outline-variant": "#464554",
        "primary": "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary": "#4fdbc8",
        "on-secondary": "#003731",
        "secondary-container": "#04b4a2",
        "on-secondary-container": "#003f38",
        "secondary-fixed": "#71f8e4",
        "secondary-fixed-dim": "#4fdbc8",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005048",
        "tertiary": "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#ca8100",
        "on-tertiary-container": "#3e2400",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "background": "#0c1326",
        "on-background": "#dbe2fc",
        "inverse-surface": "#dbe2fc",
        "inverse-on-surface": "#293044",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["IBM Plex Mono", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
      animation: {
        "shimmer": "shimmer 2s infinite linear",
        "spin-slow": "spin 8s linear infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "slide-in-right": "slideInRight 0.5s ease-out forwards",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideInRight: {
          "0%": { transform: "translateX(20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
}
